### ISSUE TITLE
Pemilihan CMS/Content Source

### ISSUE THREAD

**Issue by yudyananda** [GatsbyJS-Indonesia/official-theme#1]
@ekaone Soal manajeman konten opsinya yang kebayang supaya mudah kolaborasi sih yang git based aja (markdown, yaml, json) atau kalau ada ide lain?

**Comment by ekaone** [comment]
@yudyananda Agree git based aja (markdown), ini berarti content nya di repository kan ya..?

**Comment by yudyananda** [comment]
👍  yup, bisa di tempat source code atau repo yang berbeda. Kita anggap close aja yang ini.
