### ISSUE TITLE
Struktur Konten

### ISSUE THREAD

**Issue by yudyananda** [GatsbyJS-Indonesia/official-theme#2]
@ekaone Kebutuhan struktur konten gatsbyjs.id kira-kira gimana ya?  maksud saya seperti content type taxonomy dll

**Comment by ekaone** [comment]
@yudyananda Untuk sementara buat `Landing Page` aja kali dulu ya 😃, content-type nya yang simple dulu seperti website [Reactjs.id](https://reactjs.id/)
- Komunitas 👉 isinya bisa informasi seputar pranala gorup komunitas di indonesia (gak harus Gatsby)
- Faq 👉 pertanyaan mendasar yg berkaitan dengan pemograman
- Pranala 👉 bisa merujuk ke berbagai hal, misal tutorial, youtube dll
- (Optional) Jualan goodies (pernak-pernik), buat kas komunitas 😃

Seiring berjalannya waktu & komunitas uda cukup aktif, nanti pastinya bakal ada penambahan lainnya

Bagaimana menurut rekans @syukrie77 dan @zaiinhs, inputnya welcome banget hehe 👍

**Comment by yudyananda** [comment]
Ok, kita mulai aja dulu ya. Sementara ini kita close
